language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - nosetests
  - mypy --ignore-missing-imports -p editorconfig_git_preserve_history
  - sh .travis-scripts/clone-test.sh
